import { ToolConfig } from '../types';

export const TOOLS: ToolConfig[] = [
  // 1. ORGANIZE (10 tools)
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    title: 'Merge PDF',
    category: 'organize',
    icon: 'Combine',
    description: 'Combine multiple PDF files into one unified, structured document in seconds.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 50,
    clientSideOnly: true,
    featured: true,
    badge: 'Popular',
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    title: 'Split PDF',
    category: 'organize',
    icon: 'Scissors',
    description: 'Extract custom page ranges or separate every single page into distinct PDF files.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    title: 'Remove Pages',
    category: 'organize',
    icon: 'Trash2',
    description: 'Visually select and eliminate unwanted pages from your PDF file.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'extract-pages',
    slug: 'extract-pages',
    title: 'Extract Pages',
    category: 'organize',
    icon: 'FileOutput',
    description: 'Isolate specific pages or page selections to create a new, lightweight document.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'organize-pdf',
    slug: 'organize-pdf',
    title: 'Organize / Reorder Pages',
    category: 'organize',
    icon: 'ArrowUpDown',
    description: 'Rearrange page sequences with visual drag-and-drop thumbnail grid reordering.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    title: 'Rotate PDF',
    category: 'organize',
    icon: 'RotateCw',
    description: 'Rotate all pages or individual landscape/portrait pages by 90, 180, or 270 degrees.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'crop-pdf',
    slug: 'crop-pdf',
    title: 'Crop PDF',
    category: 'organize',
    icon: 'Crop',
    description: 'Trim page margins, eliminate borders, or adjust the bounding box of your document.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'resize-pdf',
    slug: 'resize-pdf',
    title: 'Resize / Scale PDF',
    category: 'organize',
    icon: 'Maximize2',
    description: 'Scale pages between standard paper sizes: A4, US Letter, A3, Legal, and Tabloid.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'duplicate-pages',
    slug: 'duplicate-pages',
    title: 'Duplicate Pages',
    category: 'organize',
    icon: 'Copy',
    description: 'Clone specific pages or multiply your entire document pages for handouts and batches.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'flatten-pdf',
    slug: 'flatten-pdf',
    title: 'Flatten PDF',
    category: 'organize',
    icon: 'Layers',
    description: 'Lock form fields, comments, and annotations into the immutable base visual layer.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },

  // 2. CONVERT TO PDF (12 tools)
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    title: 'Word to PDF',
    category: 'convert-to',
    icon: 'FileText',
    description: 'Convert DOCX and DOC documents into pristine, high-fidelity PDF files.',
    acceptedFileTypes: ['.docx', '.doc', '.txt'],
    maxFiles: 10,
    clientSideOnly: true,
    featured: true,
    badge: 'Popular',
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    title: 'Excel to PDF',
    category: 'convert-to',
    icon: 'FileSpreadsheet',
    description: 'Render XLSX and CSV spreadsheets into formatted, printable PDF tables.',
    acceptedFileTypes: ['.xlsx', '.xls', '.csv'],
    maxFiles: 10,
    clientSideOnly: true,
  },
  {
    id: 'powerpoint-to-pdf',
    slug: 'powerpoint-to-pdf',
    title: 'PowerPoint to PDF',
    category: 'convert-to',
    icon: 'Presentation',
    description: 'Transform presentation slide decks (PPTX, PPT) into seamless PDF presentations.',
    acceptedFileTypes: ['.pptx', '.ppt'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    title: 'JPG to PDF',
    category: 'convert-to',
    icon: 'Image',
    description: 'Convert JPEG photos into clean PDF documents with custom orientation and margins.',
    acceptedFileTypes: ['.jpg', '.jpeg'],
    maxFiles: 30,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'png-to-pdf',
    slug: 'png-to-pdf',
    title: 'PNG to PDF',
    category: 'convert-to',
    icon: 'ImagePlus',
    description: 'Turn transparent and crisp PNG graphics into multi-page or single-page PDF files.',
    acceptedFileTypes: ['.png'],
    maxFiles: 30,
    clientSideOnly: true,
  },
  {
    id: 'webp-to-pdf',
    slug: 'webp-to-pdf',
    title: 'WEBP to PDF',
    category: 'convert-to',
    icon: 'FileImage',
    description: 'Compile modern web-optimized WEBP imagery into professional documents.',
    acceptedFileTypes: ['.webp'],
    maxFiles: 30,
    clientSideOnly: true,
  },
  {
    id: 'bmp-to-pdf',
    slug: 'bmp-to-pdf',
    title: 'BMP / TIFF to PDF',
    category: 'convert-to',
    icon: 'Image',
    description: 'Convert raw bitmap pictures and uncompressed graphics into durable PDFs.',
    acceptedFileTypes: ['.bmp', '.tiff', '.tif'],
    maxFiles: 20,
    clientSideOnly: true,
  },
  {
    id: 'heic-to-pdf',
    slug: 'heic-to-pdf',
    title: 'HEIC to PDF',
    category: 'convert-to',
    icon: 'Smartphone',
    description: 'Transform Apple smartphone camera captures (HEIC/HEIF) into universal PDFs.',
    acceptedFileTypes: ['.heic', '.heif'],
    maxFiles: 20,
    clientSideOnly: true,
  },
  {
    id: 'svg-to-pdf',
    slug: 'svg-to-pdf',
    title: 'SVG to PDF',
    category: 'convert-to',
    icon: 'Vector',
    description: 'Convert scalable vector graphics into crisp, infinite-resolution vector PDFs.',
    acceptedFileTypes: ['.svg'],
    maxFiles: 10,
    clientSideOnly: true,
  },
  {
    id: 'txt-to-pdf',
    slug: 'txt-to-pdf',
    title: 'TXT / RTF to PDF',
    category: 'convert-to',
    icon: 'AlignLeft',
    description: 'Format plain text and rich text documents into clean, typeset PDF pages.',
    acceptedFileTypes: ['.txt', '.rtf', '.log'],
    maxFiles: 10,
    clientSideOnly: true,
  },
  {
    id: 'html-to-pdf',
    slug: 'html-to-pdf',
    title: 'HTML / Code to PDF',
    category: 'convert-to',
    icon: 'Code2',
    description: 'Render web HTML files, CSS, or markdown code snippets directly into PDF.',
    acceptedFileTypes: ['.html', '.htm', '.md'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'epub-to-pdf',
    slug: 'epub-to-pdf',
    title: 'EPUB to PDF',
    category: 'convert-to',
    icon: 'BookOpen',
    description: 'Convert electronic ebooks and publication files into printable PDF format.',
    acceptedFileTypes: ['.epub'],
    maxFiles: 3,
    clientSideOnly: true,
  },

  // 3. CONVERT FROM PDF (12 tools)
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    title: 'PDF to Word (DOCX)',
    category: 'convert-from',
    icon: 'FileType2',
    description: 'Extract full textual structure and paragraphs into editable Microsoft Word documents.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
    featured: true,
    badge: 'Popular',
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    title: 'PDF to Excel (XLSX)',
    category: 'convert-from',
    icon: 'Table',
    description: 'Detect tabular rows and columns inside your PDF and export directly to spreadsheet.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'pdf-to-powerpoint',
    slug: 'pdf-to-powerpoint',
    title: 'PDF to PowerPoint',
    category: 'convert-from',
    icon: 'Sliders',
    description: 'Convert PDF document pages into presentation slides ready for keynote delivery.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    title: 'PDF to JPG',
    category: 'convert-from',
    icon: 'FileImage',
    description: 'Render every PDF page into high-resolution JPG images packaged in a zip archive.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'pdf-to-png',
    slug: 'pdf-to-png',
    title: 'PDF to PNG',
    category: 'convert-from',
    icon: 'Images',
    description: 'Export pristine pixel-perfect PNG graphics for every page at 300 DPI.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'pdf-to-txt',
    slug: 'pdf-to-txt',
    title: 'PDF to TXT',
    category: 'convert-from',
    icon: 'FileText',
    description: 'Extract raw textual contents and headings into a clean text file without formatting.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'pdf-to-markdown',
    slug: 'pdf-to-markdown',
    title: 'PDF to Markdown',
    category: 'convert-from',
    icon: 'FileCode',
    description: 'Transform PDF headings, lists, quotes, and tables into GitHub Flavored Markdown.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'pdf-to-html',
    slug: 'pdf-to-html',
    title: 'PDF to HTML',
    category: 'convert-from',
    icon: 'Globe',
    description: 'Convert PDF contents into responsive, styled HTML web pages with CSS.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'pdf-to-epub',
    slug: 'pdf-to-epub',
    title: 'PDF to EPUB',
    category: 'convert-from',
    icon: 'Book',
    description: 'Re-flow your PDF book pages into an EPUB compatible with Kindle and e-readers.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 2,
    clientSideOnly: true,
  },
  {
    id: 'pdf-to-pdfa',
    slug: 'pdf-to-pdfa',
    title: 'PDF to PDF/A',
    category: 'convert-from',
    icon: 'Archive',
    description: 'Convert to ISO-standard PDF/A for verified legal archiving and long-term storage.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'extract-images',
    slug: 'extract-images',
    title: 'Extract Images from PDF',
    category: 'convert-from',
    icon: 'ImageDown',
    description: 'Extract all embedded graphics, photos, and illustrations in their native resolution.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'pdf-to-csv',
    slug: 'pdf-to-csv',
    title: 'PDF to CSV',
    category: 'convert-from',
    icon: 'Table2',
    description: 'Parse bank statements, receipts, and invoice tables into structured CSV comma rows.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },

  // 4. OPTIMIZE (6 tools)
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    title: 'Compress PDF',
    category: 'optimize',
    icon: 'Minimize2',
    description: 'Reduce file size by up to 85% while maintaining optical clarity for email & web.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 10,
    clientSideOnly: true,
    featured: true,
    badge: 'Popular',
  },
  {
    id: 'grayscale-pdf',
    slug: 'grayscale-pdf',
    title: 'Grayscale PDF',
    category: 'optimize',
    icon: 'Moon',
    description: 'Convert color vector artwork, text, and images into black & white for ink saving.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'repair-pdf',
    slug: 'repair-pdf',
    title: 'Repair PDF',
    category: 'optimize',
    icon: 'Activity',
    description: 'Fix corrupt cross-reference tables, invalid xref streams, and unreadable PDF trees.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 3,
    clientSideOnly: true,
  },
  {
    id: 'ocr-engine',
    slug: 'ocr-engine',
    title: 'OCR Text Recognition',
    category: 'optimize',
    icon: 'Eye',
    description: 'Recognize scanned text within images and produce fully searchable, copyable PDFs.',
    acceptedFileTypes: ['.pdf', '.jpg', '.png'],
    maxFiles: 5,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'rasterize-pdf',
    slug: 'rasterize-pdf',
    title: 'Rasterize PDF',
    category: 'optimize',
    icon: 'Grid',
    description: 'Bake entire PDF pages into static bitmap renders to prevent any vector scraping.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'deskew-pages',
    slug: 'deskew-pages',
    title: 'Deskew Scanned Pages',
    category: 'optimize',
    icon: 'Compass',
    description: 'Detect tilted scanner page angles and automatically straighten page orientations.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },

  // 5. SECURITY (8 tools)
  {
    id: 'protect-pdf',
    slug: 'protect-pdf',
    title: 'Protect PDF (Password)',
    category: 'security',
    icon: 'Lock',
    description: 'Encrypt your document with 128-bit/256-bit AES encryption and confidential passwords.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock-pdf',
    title: 'Unlock PDF',
    category: 'security',
    icon: 'Unlock',
    description: 'Remove password protection and print/copy restrictions from unlocked documents.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'redact-pdf',
    slug: 'redact-pdf',
    title: 'Redact PDF',
    category: 'security',
    icon: 'SquareSlash',
    description: 'Permanently black out sensitive PII, social security numbers, and confidential text.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 2,
    clientSideOnly: true,
  },
  {
    id: 'watermark-pdf',
    slug: 'watermark-pdf',
    title: 'Watermark PDF',
    category: 'security',
    icon: 'Stamp',
    description: 'Stamp custom text or visual emblems across all pages with customizable opacity.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 10,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'sign-pdf',
    slug: 'sign-pdf',
    title: 'e-Sign PDF',
    category: 'security',
    icon: 'FileSignature',
    description: 'Draw, type, or upload your official digital signature and place it anywhere on pages.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 2,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'sanitize-metadata',
    slug: 'sanitize-metadata',
    title: 'Sanitize Metadata',
    category: 'security',
    icon: 'ShieldAlert',
    description: 'Scrub author name, GPS coordinates, editing software, and creation timestamps.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'restrict-permissions',
    slug: 'restrict-permissions',
    title: 'Restrict Permissions',
    category: 'security',
    icon: 'ShieldOff',
    description: 'Disable copying, high-resolution printing, and content modification flags.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'verify-signatures',
    slug: 'verify-signatures',
    title: 'Verify Signatures',
    category: 'security',
    icon: 'BadgeCheck',
    description: 'Inspect cryptographic X.509 certificates and audit signature timestamp authenticity.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 2,
    clientSideOnly: true,
  },

  // 6. EDIT & FORMS (10 tools)
  {
    id: 'edit-text',
    slug: 'edit-text',
    title: 'Edit PDF Text',
    category: 'edit',
    icon: 'Type',
    description: 'Add custom text boxes, modify typography, adjust fonts, and restyle content.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'annotate-pdf',
    slug: 'annotate-pdf',
    title: 'Annotate PDF',
    category: 'edit',
    icon: 'Edit3',
    description: 'Draw freehand callouts, arrows, geometric circles, and stick notes on any page.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'highlight-pdf',
    slug: 'highlight-pdf',
    title: 'Highlight PDF',
    category: 'edit',
    icon: 'Highlighter',
    description: 'Apply translucent neon highlights to emphasize critical phrases and paragraphs.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'page-numbers',
    slug: 'page-numbers',
    title: 'Add Page Numbers',
    category: 'edit',
    icon: 'Binary',
    description: 'Insert dynamic page numbering (e.g. "Page X of Y") at top, bottom, or corners.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'form-builder',
    slug: 'form-builder',
    title: 'PDF Form Builder',
    category: 'edit',
    icon: 'CheckSquare',
    description: 'Construct interactive AcroForm fields, checkboxes, text inputs, and submit buttons.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'fill-forms',
    slug: 'fill-forms',
    title: 'Fill PDF Forms',
    category: 'edit',
    icon: 'FormInput',
    description: 'Interactively fill out existing form fields and save the completed document.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'header-footer',
    slug: 'header-footer',
    title: 'Header & Footer',
    category: 'edit',
    icon: 'PanelTop',
    description: 'Apply custom corporate headers, document titles, dates, and footers across pages.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'bates-stamping',
    slug: 'bates-stamping',
    title: 'Bates Stamping',
    category: 'edit',
    icon: 'Hash',
    description: 'Index legal discovery documents with sequential bates numbering prefixes & padding.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 5,
    clientSideOnly: true,
  },
  {
    id: 'attach-files',
    slug: 'attach-files',
    title: 'Attach Files to PDF',
    category: 'edit',
    icon: 'Paperclip',
    description: 'Embed external spreadsheets, source code, or audio clips as PDF attachments.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'extract-attachments',
    slug: 'extract-attachments',
    title: 'Extract Attachments',
    category: 'edit',
    icon: 'FolderDown',
    description: 'View and download embedded binary attachments packaged inside your PDF.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },

  // 7. AI & INTELLIGENCE (6 tools)
  {
    id: 'ai-summarizer',
    slug: 'ai-summarizer',
    title: 'AI Summarizer',
    category: 'ai',
    icon: 'Sparkles',
    description: 'Summarize 100+ page contracts, academic papers, and manuals in seconds with Gemini.',
    acceptedFileTypes: ['.pdf', '.txt', '.docx'],
    maxFiles: 1,
    clientSideOnly: false,
    featured: true,
    badge: 'Gemini AI',
  },
  {
    id: 'ai-translator',
    slug: 'ai-translator',
    title: 'AI Document Translator',
    category: 'ai',
    icon: 'Languages',
    description: 'Translate documents into 50+ languages while preserving paragraphs and context.',
    acceptedFileTypes: ['.pdf', '.txt'],
    maxFiles: 1,
    clientSideOnly: false,
    featured: true,
    badge: 'Gemini AI',
  },
  {
    id: 'chat-with-pdf',
    slug: 'chat-with-pdf',
    title: 'Chat with PDF',
    category: 'ai',
    icon: 'MessageSquare',
    description: 'Converse directly with your PDF, ask deep contextual questions, and retrieve citations.',
    acceptedFileTypes: ['.pdf', '.txt'],
    maxFiles: 1,
    clientSideOnly: false,
    featured: true,
    badge: 'Gemini AI',
  },
  {
    id: 'document-comparison',
    slug: 'document-comparison',
    title: 'Document Comparison (Diff)',
    category: 'ai',
    icon: 'GitCompare',
    description: 'Compare two contract versions with semantic intelligence highlighting critical changes.',
    acceptedFileTypes: ['.pdf', '.txt'],
    maxFiles: 2,
    clientSideOnly: false,
    badge: 'Gemini AI',
  },
  {
    id: 'quiz-generator',
    slug: 'quiz-generator',
    title: 'Flashcard & Quiz Generator',
    category: 'ai',
    icon: 'GraduationCap',
    description: 'Generate interactive study flashcards and multiple-choice quizzes from study notes.',
    acceptedFileTypes: ['.pdf', '.txt'],
    maxFiles: 1,
    clientSideOnly: false,
    badge: 'Gemini AI',
  },
  {
    id: 'form-detector',
    slug: 'form-detector',
    title: 'Smart Form Detector',
    category: 'ai',
    icon: 'ScanLine',
    description: 'Automatically identify blanks, signature lines, and form data models in flat PDFs.',
    acceptedFileTypes: ['.pdf', '.jpg', '.png'],
    maxFiles: 1,
    clientSideOnly: false,
    badge: 'Gemini AI',
  },

  // 8. UTILITIES (8 tools)
  {
    id: 'n-up-pdf',
    slug: 'n-up-pdf',
    title: 'N-Up Layout (Multi-Page)',
    category: 'utilities',
    icon: 'LayoutGrid',
    description: 'Print 2, 4, or 8 pages onto a single sheet to economize on paper and print handouts.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'booklet-creator',
    slug: 'booklet-creator',
    title: 'Booklet Creator',
    category: 'utilities',
    icon: 'BookMarked',
    description: 'Impose pages into saddle-stitch booklet order ready for folding and binding.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'split-in-half',
    slug: 'split-in-half',
    title: 'Split Pages in Half',
    category: 'utilities',
    icon: 'Columns2',
    description: 'Slice two-page book scans down the middle into individual, portrait pages.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'reverse-order',
    slug: 'reverse-order',
    title: 'Reverse Page Order',
    category: 'utilities',
    icon: 'ArrowDownUp',
    description: 'Instantly reverse page order from back-to-front for flipped printer feeds.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'invert-colors',
    slug: 'invert-colors',
    title: 'Invert Colors (Dark Mode)',
    category: 'utilities',
    icon: 'Contrast',
    description: 'Transform white backgrounds into dark mode for comfortable nighttime reading.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'camera-scan',
    slug: 'camera-scan',
    title: 'Web Camera Scan to PDF',
    category: 'utilities',
    icon: 'Camera',
    description: 'Use your webcam to snap physical paper documents and instantly compile them into PDF.',
    acceptedFileTypes: ['.jpg', '.png'],
    maxFiles: 20,
    clientSideOnly: true,
    featured: true,
  },
  {
    id: 'add-margins',
    slug: 'add-margins',
    title: 'Add Margins & Padding',
    category: 'utilities',
    icon: 'Minimize',
    description: 'Pad pages with configurable whitespace margins for hole punching and binder rings.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
  {
    id: 'metadata-editor',
    slug: 'metadata-editor',
    title: 'PDF Metadata Editor',
    category: 'utilities',
    icon: 'Info',
    description: 'View and edit Title, Author, Subject, Keywords, Creator, and Producer tags.',
    acceptedFileTypes: ['.pdf'],
    maxFiles: 1,
    clientSideOnly: true,
  },
];
